#pragma once
#define __OSX_AVAILABLE(x)
#define __IOS_AVAILABLE(x)
#define __TVOS_AVAILABLE(x)
#define __WATCHOS_AVAILABLE(x)
#define __BRIDGEOS_AVAILABLE(x)
#define __OSX_DEPRECATED(...)
#define __IOS_DEPRECATED(...)
#define __TVOS_DEPRECATED(...)
#define __WATCHOS_DEPRECATED(...)
#define __BRIDGEOS_DEPRECATED(...)
#define __OSX_UNAVAILABLE
#define __IOS_UNAVAILABLE
#define __TVOS_UNAVAILABLE
#define __WATCHOS_UNAVAILABLE
#define __API_AVAILABLE(...)
#define __API_UNAVAILABLE(...)
#define __API_DEPRECATED(...)
#define API_AVAILABLE(...)
#define API_UNAVAILABLE(...)
#define API_DEPRECATED(...)
#define API_DEPRECATED_WITH_REPLACEMENT(...)
